name: Deploy to Render

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  NPM_CACHE_FOLDER: ~/.npm
  NODE_MODULES_CACHE_FOLDER: ~/.npm

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run type checking
      run: npx tsc --noEmit
      
    - name: Check for security vulnerabilities
      run: npm audit --audit-level=moderate || true

  test-and-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Test build output
      run: |
        echo "🔍 Verifying build output..."
        
        # Vérifier que le build a créé les fichiers nécessaires
        if [ ! -d "dist" ]; then
          echo "❌ Build failed: dist directory not found"
          exit 1
        fi
        
        # Vérifier la taille du bundle (optimisation éco-conception)
        BUNDLE_SIZE=$(du -sh dist | cut -f1)
        echo "📦 Bundle size: $BUNDLE_SIZE"
        
        # Vérifier que les assets sont présents
        if [ ! -f "dist/index.html" ]; then
          echo "❌ Build failed: index.html not found"
          exit 1
        fi
        
        # Vérifier la présence des fichiers JS et CSS
        JS_FILES=$(find dist -name "*.js" | wc -l)
        CSS_FILES=$(find dist -name "*.css" | wc -l)
        echo "📁 JavaScript files: $JS_FILES"
        echo "📁 CSS files: $CSS_FILES"
        
        # Vérifier la taille des assets
        TOTAL_SIZE=$(du -sh dist | cut -f1)
        echo "📊 Total build size: $TOTAL_SIZE"
        
        echo "✅ Build verification successful"
        
    - name: Performance audit
      run: |
        echo "⚡ Performance audit..."
        
        # Vérifier la taille des bundles JavaScript
        JS_BUNDLES=$(find dist -name "*.js" -exec du -h {} \; | sort -hr)
        echo "📦 JavaScript bundles:"
        echo "$JS_BUNDLES"
        
        # Vérifier la compression
        if command -v gzip >/dev/null 2>&1; then
          echo "🗜️ Checking compression..."
          for file in dist/*.js dist/*.css; do
            if [ -f "$file" ]; then
              ORIGINAL_SIZE=$(du -h "$file" | cut -f1)
              COMPRESSED_SIZE=$(gzip -c "$file" | wc -c | numfmt --to=iec)
              echo "  $(basename "$file"): $ORIGINAL_SIZE → $COMPRESSED_SIZE (gzipped)"
            fi
          done
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          dist/
          backend/
          package.json
          package-lock.json
        retention-days: 7

  deploy-to-render:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    environment: production
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./
        
    - name: Deploy to Render
      id: deploy
      run: |
        echo "🚀 Deploying to Render..."
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        
        # Déclencher un nouveau déploiement via l'API Render
        if [ -n "${{ secrets.RENDER_SERVICE_ID }}" ] && [ -n "${{ secrets.RENDER_API_KEY }}" ]; then
          echo "📡 Triggering Render deployment..."
          
          DEPLOY_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -d '{"clearCache": "do_not_clear"}')
          
          if [ $? -eq 0 ]; then
            echo "✅ Deploy trigger successful"
            echo "response=$DEPLOY_RESPONSE" >> $GITHUB_OUTPUT
          else
            echo "❌ Deploy trigger failed"
            exit 1
          fi
        else
          echo "ℹ️ Render secrets not configured, skipping deployment"
          exit 1
        fi
        
    - name: Wait for deployment
      run: |
        echo "⏳ Waiting for deployment to complete..."
        sleep 60
        
    - name: Verify deployment
      id: verify
      run: |
        echo "🔍 Verifying deployment..."
        
        # Vérifier que l'application répond
        if [ -n "${{ secrets.RENDER_URL }}" ]; then
          echo "🌐 Testing deployment at ${{ secrets.RENDER_URL }}"
          
          # Test de connectivité avec retry
          MAX_RETRIES=5
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "🔄 Attempt $((RETRY_COUNT + 1))/$MAX_RETRIES"
            
            # Test de la page principale
            if curl -f -s -m 30 "${{ secrets.RENDER_URL }}" > /dev/null; then
              echo "✅ Main page responding"
              break
            else
              echo "⚠️ Main page not responding, retrying..."
              RETRY_COUNT=$((RETRY_COUNT + 1))
              sleep 30
            fi
          done
          
          # Test de l'API
          if curl -f -s -m 30 "${{ secrets.RENDER_URL }}/api/server" > /dev/null; then
            echo "✅ API endpoint responding"
          else
            echo "❌ API endpoint not responding"
            exit 1
          fi
          
          # Test des performances
          echo "⚡ Performance testing..."
          START_TIME=$(date +%s%N)
          curl -s "${{ secrets.RENDER_URL }}" > /dev/null
          END_TIME=$(date +%s%N)
          RESPONSE_TIME=$(( (END_TIME - START_TIME) / 1000000 ))
          echo "📊 Response time: ${RESPONSE_TIME}ms"
          
          if [ $RESPONSE_TIME -gt 5000 ]; then
            echo "⚠️ Slow response time: ${RESPONSE_TIME}ms"
          fi
          
        else
          echo "ℹ️ RENDER_URL not configured, skipping verification"
          exit 1
        fi

  notify-deployment:
    needs: [deploy-to-render]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Deployment Summary
      run: |
        echo "🚀 Deployment Summary"
        echo "===================="
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Author: ${{ github.actor }}"
        echo "Deployment URL: ${{ secrets.RENDER_URL }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "Run ID: ${{ github.run_id }}"
        
        if [ "${{ needs.deploy-to-render.result }}" == "success" ]; then
          echo "✅ Deploy: SUCCESS"
          echo "🎉 Application deployed successfully!"
        else
          echo "❌ Deploy: FAILED"
          echo "💥 Deployment failed. Check the logs for details."
        fi
        
        echo ""
        echo "📋 Build Information:"
        echo "  - Node.js version: ${{ env.NODE_VERSION }}"
        echo "  - Build timestamp: $(date -u)"
        echo "  - Repository: ${{ github.repository }}"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "🚨 Deployment failed!"
        echo "Check the workflow logs for more details:"
        echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
 